#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'sherlockAndAnagrams' function below.
#
# The function is expected to return an INTEGER.
# The function accepts STRING s as parameter.
#

def sherlockAndAnagrams(s):
    count = 0
    n = len(s)
    for length in range(1, n):           
        for i in range(n - length):      
            for j in range(i + 1, n - length + 1): 
                sub1 = sorted(s[i:i + length])
                sub2 = sorted(s[j:j + length])
                if sub1 == sub2:
                    count += 1
    return count

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    q = int(input().strip())

    for q_itr in range(q):
        s = input()

        result = sherlockAndAnagrams(s)

        fptr.write(str(result) + '\n')

    fptr.close()
